# Generated by Django 5.0.4 on 2024-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='api.tag', verbose_name='Tags'),
        ),
    ]
